required = [
	"golang.org/x/tools/cmd/guru"
]

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "kuroku.io/margocode"

[[constraint]]
  name = "github.com/rogpeppe/go-internal"
  version = "1.3.0"

[[override]]
  name = "github.com/russross/blackfriday"
  version = "1.5.2"
